// Seed predlozi za demo mode (isti kao u supabase-setup.sql)
let n = 0
const s = (title, description, category, author_name, votes_count) => ({
  id: 'demo-' + (++n),
  created_at: new Date(Date.now() - n * 36e5).toISOString(),
  title, description, category, author_name, votes_count,
  status: 'new',
})

export const DEMO_SUGGESTIONS = [
  s('Permanent Infiniportable as a chase item',
    'A permanent (non-breaking) Infiniportable would be a huge QoL for everyone, including F2P. The item already exists in-game — make the permanent version a chase item in events/MS instead of leaving boots nobody buys on the market.',
    'qol', 'RGPixels & Kirin', 14),
  s('Batch crafting for T5 cooking recipes',
    'T5 cooking has no batch option — each food is 2h+. Even a 6x batch (12-18h) would matter for players pushing cooking to level 100. Could also work as a T6 VIP utility.',
    'qol', 'ChuckFresco & RGPixels', 11),
  s('New Merchant Ship rewards — controlled animal batches',
    'MS needs new rewards or players hoard buoy bucks like Neon Zone (600 players hold 10k+, 20 hold 500k+). Suggested: small controlled batches (20-25) of dragons/ducks/goats/pigs — NOT a mass release that tanks values like CH2 pets.',
    'economy', 'GebesTurtle, Kirin & Jocca', 10),
  s('Ensure Stacked offer tasks can actually appear',
    'Some Stacked offers require tasks (e.g. T5 turn-ins) that never appear on the taskboard no matter how many tasks you submit. A blocker should be about skill/resources, not about the system never giving you the task.',
    'bug', 'nozomi & pOrenji', 9),
  s('Portals between your own farms',
    'If you own 2+ farms, a direct portal between them. Multi-land owners travel constantly; this is a natural multi-land bonus.',
    'qol', 'Brad C³', 8),
  s("Remove banned accounts' items from lands",
    "Banned botters just move their land to a fresh account and keep benefiting. Removing banned accounts' items/benefits from lands would make bans actually matter.",
    'economy', 'mixyero', 8),
  s('Adjust T4 baby animal drop rates for current DAU',
    'T4 babies are so rare that recipes depending on them are unaffordable. Rates were tuned for a bigger player base — revisit them for current DAU.',
    'economy', 'ChuckFresco', 7),
  s('Release more potion tables (limited batch)',
    'Potion tables were carnival prizes, supply unknown (~140?), price ~590k and rising. Only early players benefit. Release a small controlled batch via gacha/competition/MS.',
    'economy', 'Dynamic Warrior & Nenzy', 6),
  s('Fix the winery loop before adding new content',
    'Winery content was devalued after players invested heavily in it. Fix that loop (wine demand in MS contracts, goose bar turn-ins) before releasing more content on top.',
    'economy', 'Kirin & RGPixels', 6),
  s('Communicate staking rewards & community treasury status',
    "In-game pixel staking rewards are a month late and there's zero news about the community treasury. Even a short monthly status update would rebuild trust.",
    'economy', 'Golf', 5),
  s('Pets that assist while farming',
    'Give pets a small active role during farming. Increases pet usefulness, helps the pet economy, and makes long farming sessions less of a grind.',
    'content', 'Bud Spencer', 5),
  s('Goose bar: turn in wines for surprise rewards',
    'Let players bring wines to Goose for surprise items. Creates real wine demand and a social hub — the bar is empty now.',
    'content', 'mixyero', 4),
  s('Pet battles with limited fights per pet',
    'Pet battle mode where each pet can only battle X times — creates a reason to own multiple pets without hurting genesis utility.',
    'content', 'RGPixels', 4),
  s("Direct teleport into your land's house",
    'Small QoL: teleport straight into the house on your land instead of walking in every time.',
    'qol', 'Bud Spencer', 3),
  s('Composter as a new chase item',
    'Composters already exist in-game and players want more — a natural chase item candidate for events or MS.',
    'content', 'RGPixels', 3),
  s('Equip two pets at high level',
    'Allow dual pets for high-level players (e.g. 600+). A prestige perk that also drives demand for pets.',
    'content', 'Brad C³', 2),
]
